In [1]:
import pandas as pd

In [2]:
path = "C:/Users/Ufuk Altan/Downloads/Downloads/Data Science/PyFinance/04 - Intrinsic Value/"
df = pd.read_csv(path + '50-current-ratio.csv', index_col = 0)
df.head()

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,...,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2020-09-30,1.36,2.53,1.11,3.41,5.51,1.64,0.27,1.91,1.48,NaN,...,NaN,1.26,1.36,1.07,2.08,NaN,0.57,4.24,1.64,1.29
2020-06-30,1.47,2.52,1.18,3.41,6.03,1.25,0.30,1.55,1.25,NaN,...,NaN,1.14,1.22,0.91,2.20,NaN,0.61,3.92,1.63,1.24
2020-03-31,1.50,2.90,1.08,3.66,4.60,1.24,0.33,1.25,1.31,NaN,...,NaN,1.01,1.11,1.90,1.32,NaN,0.71,3.49,1.30,1.22
2019-12-31,1.60,2.80,1.10,3.37,4.40,1.14,0.39,1.27,1.26,NaN,...,NaN,1.07,1.16,0.98,5.19,NaN,0.54,4.13,1.34,1.11
2019-09-30,1.54,2.85,1.10,3.78,4.66,1.08,0.44,1.56,1.26,NaN,...,NaN,1.12,1.17,0.84,3.43,NaN,0.58,4.34,1.32,1.11

In [3]:
df.index = pd.to_datetime(df.index)
df.index

DatetimeIndex(['2020-09-30', '2020-06-30', '2020-03-31', '2019-12-31',
               '2019-09-30', '2019-06-30', '2019-03-31', '2018-12-31',
               '2018-09-30', '2018-06-30',
               ...
               '2007-05-31', '2007-02-28', '2006-11-30', '2006-08-31',
               '2006-05-31', '2006-02-28', '2005-11-30', '2005-08-31',
               '2005-05-31', '2005-02-28'],
              dtype='datetime64[ns]', length=191, freq=None)

In [4]:
df.loc[:'2010-01-01']

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,...,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2009-12-31,2.55,2.04,1.33,10.62,0.0,0.0,0.45,2.41,1.82,NaN,...,NaN,1.42,1.90,1.14,1.89,NaN,0.67,3.85,1.25,1.49
2009-09-30,2.74,1.82,1.40,11.35,NaN,0.0,0.42,2.08,1.85,NaN,...,NaN,1.40,1.95,1.02,1.94,NaN,0.64,3.69,1.26,1.41
2009-06-30,2.11,1.82,1.46,11.91,NaN,0.0,0.40,2.16,1.79,NaN,...,NaN,1.37,1.57,1.27,1.91,NaN,0.73,3.91,1.25,1.42
2009-03-31,2.46,1.71,1.40,10.11,NaN,NaN,0.42,1.94,1.63,NaN,...,NaN,1.37,1.40,1.56,1.82,NaN,0.78,4.30,1.17,1.29
2008-12-31,2.38,1.59,1.30,8.77,0.0,0.0,0.42,1.75,1.65,NaN,...,NaN,1.14,0.95,1.39,1.53,NaN,0.70,3.78,1.08,1.13
2008-09-30,2.64,1.53,1.41,8.08,NaN,NaN,0.50,1.56,1.61,NaN,...,NaN,1.20,1.99,0.98,1.37,NaN,0.74,3.57,1.10,1.12
2008-06-30,3.04,1.45,1.32,6.96,NaN,NaN,0.49,1.77,1.64,NaN,...,NaN,1.17,2.41,1.28,1.36,NaN,0.66,3.42,1.26,1.00
2008-03-31,2.78,1.54,1.12,6.29,NaN,NaN,0.52,1.73,1.53,NaN,...,NaN,1.17,3.00,1.17,1.39,NaN,0.73,3.23,1.30,1.07
2007-12-31,2.49,1.71,1.39,8.49,NaN,NaN,0.58,1.12,1.51,NaN,...,NaN,1.17,2.27,0.80,1.40,NaN,0.66,3.42,1.15,1.20
2007-09-30,2.37,1.58,1.48,8.83,NaN,NaN,0.60,0.76,1.50,NaN,...,NaN,1.27,2.57,1.06,1.62,NaN,0.64,3.97,1.13,1.22
2007-06-30,2.68,1.69,1.48,11.26,NaN,NaN,0.60,0.00,1.36,NaN,...,NaN,1.31,2.10,1.27,1.62,NaN,0.76,4.21,1.06,1.31
2007-03-31,2.92,1.98,1.41,11.23,NaN,NaN,0.65,0.00,1.26,NaN,...,NaN,1.29,2.23,1.27,1.58,NaN,0.66,4.34,1.22,1.36
2006-12-31,2.27,2.03,1.33,10.00,NaN,NaN,0.62,0.00,1.20,NaN,...,NaN,1.28,1.91,1.76,1.40,NaN,0.76,3.78,1.21,1.40
2006-09-30,2.25,2.06,1.31,9.75,NaN,NaN,0.63,NaN,2.59,NaN,...,NaN,1.32,2.52,1.28,1.37,NaN,0.78,3.55,1.24,1.30
2006-06-30,2.49,2.18,1.53,11.31,NaN,NaN,0.64,NaN,2.59,NaN,...,NaN,1.36,2.28,1.35,1.28,NaN,0.64,3.52,1.20,1.59
2006-03-31,2.53,2.54,1.55,9.75,NaN,NaN,0.65,NaN,2.56,NaN,...,NaN,1.43,2.29,1.43,1.39,NaN,0.62,3.86,1.23,1.55
2005-12-31,2.40,2.79,1.54,12.08,NaN,NaN,0.80,NaN,2.49,NaN,...,NaN,1.37,1.89,1.51,1.30,NaN,0.69,3.96,1.15,1.65
2005-09-30,2.95,2.93,1.62,14.97,NaN,NaN,0.86,NaN,2.54,NaN,...,NaN,1.37,2.35,0.92,1.27,NaN,0.76,4.07,1.30,1.45
2005-06-30,3.00,2.89,1.68,8.14,NaN,NaN,0.92,NaN,2.47,NaN,...,NaN,1.65,1.70,0.99,1.36,NaN,0.74,4.03,1.33,2.00
2005-03-31,2.69,2.89,1.67,8.03,NaN,NaN,0.92,NaN,2.22,NaN,...,NaN,1.58,2.09,1.05,1.32,NaN,0.80,4.14,1.29,1.96
2009-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.87,...,NaN,NaN,NaN,NaN,NaN,2.23,NaN,NaN,NaN,NaN
2009-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.85,...,NaN,NaN,NaN,NaN,NaN,2.33,NaN,NaN,NaN,NaN
2009-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.85,...,NaN,NaN,NaN,NaN,NaN,2.37,NaN,NaN,NaN,NaN
2009-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.88,...,NaN,NaN,NaN,NaN,NaN,2.28,NaN,NaN,NaN,NaN
2008-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.88,...,NaN,NaN,NaN,NaN,NaN,2.23,NaN,NaN,NaN,NaN
2008-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.91,...,NaN,NaN,NaN,NaN,NaN,1.99,NaN,NaN,NaN,NaN
2008-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.83,...,NaN,NaN,NaN,NaN,NaN,2.07,NaN,NaN,NaN,NaN
2008-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.82,...,NaN,NaN,NaN,NaN,NaN,1.89,NaN,NaN,NaN,NaN
2007-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.85,...,NaN,NaN,NaN,NaN,NaN,3.98,NaN,NaN,NaN,NaN
2007-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.84,...,NaN,NaN,NaN,NaN,NaN,3.76,NaN,NaN,NaN,NaN
2007-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.87,...,NaN,NaN,NaN,NaN,NaN,3.09,NaN,NaN,NaN,NaN
2007-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.90,...,NaN,NaN,NaN,NaN,NaN,3.04,NaN,NaN,NaN,NaN
2006-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.85,...,NaN,NaN,NaN,NaN,NaN,3.13,NaN,NaN,NaN,NaN
2006-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.85,...,NaN,NaN,NaN,NaN,NaN,2.35,NaN,NaN,NaN,NaN
2006-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.87,...,NaN,NaN,NaN,NaN,NaN,2.36,NaN,NaN,NaN,NaN
2006-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.90,...,NaN,NaN,NaN,NaN,NaN,1.83,NaN,NaN,NaN,NaN
2005-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.89,...,NaN,NaN,NaN,NaN,NaN,1.66,NaN,NaN,NaN,NaN
2005-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.82,...,NaN,NaN,NaN,NaN,NaN,1.98,NaN,NaN,NaN,NaN
2005-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.81,...,NaN,NaN,NaN,NaN,NaN,2.20,NaN,NaN,NaN,NaN
2005-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.90,...,NaN,NaN,NaN,NaN,NaN,2.53,NaN,NaN,NaN,NaN
2009-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
col = df.resample('Q', convention = 'end').agg('mean').transpose()['2020-09-30']

In [9]:
col > 1

AAPL      True
MSFT      True
AMZN      True
GOOG      True
FB        True
TSLA      True
BRK.A    False
V         True
JNJ       True
WMT      False
JPM      False
MA        True
PG       False
UNH      False
DIS       True
NVDA      True
HD        True
PYPL      True
BAC      False
VZ        True
ADBE      True
CMCSA    False
NFLX      True
KO        True
NKE       True
MRK       True
PEP      False
T        False
PFE       True
INTC      True
CRM       True
ABT       True
ORCL      True
ABBV     False
CSCO      True
TMO       True
AVGO      True
XOM      False
ACN       True
QCOM      True
COST      True
CVX       True
LLY       True
MCD       True
DHR       True
MDT       True
NEE      False
TXN       True
HON       True
UPS       True
Name: 2020-09-30 00:00:00, dtype: bool