In [1]:
import pandas as pd

In [2]:
path = "C:/Users/Ufuk Altan/Downloads/Downloads/Data Science/PyFinance/04 - Intrinsic Value/"
df = pd.read_csv(path + '50-de-ratio.csv', index_col = 0)
df.head()

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,...,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2020-09-30,3.96,1.44,2.41,0.41,0.24,1.71,0.98,1.24,1.65,NaN,...,NaN,0.69,7.80,-6.98,0.92,NaN,2.01,1.19,2.47,10.13
2020-06-30,3.39,1.55,2.50,0.34,0.27,2.56,0.98,1.19,1.52,NaN,...,NaN,0.66,8.82,-6.28,0.97,NaN,1.93,1.28,2.46,13.18
2020-03-31,3.09,1.49,2.39,0.34,0.31,2.71,1.03,1.11,1.53,NaN,...,NaN,0.63,11.86,-6.44,1.22,NaN,1.95,1.24,2.21,17.38
2019-12-31,2.80,1.57,2.63,0.37,0.32,3.60,0.91,1.12,1.65,NaN,...,NaN,0.64,13.56,-6.79,1.05,NaN,1.85,1.02,2.14,16.62
2019-09-30,2.74,1.63,2.52,0.35,0.32,3.77,0.96,1.09,1.67,NaN,...,NaN,0.64,9.94,-6.33,0.85,NaN,1.84,1.00,2.28,8.56

In [12]:
df.index = pd.to_datetime(df.index)
df.index

DatetimeIndex(['2020-09-30', '2020-06-30', '2020-03-31', '2019-12-31',
               '2019-09-30', '2019-06-30', '2019-03-31', '2018-12-31',
               '2018-09-30', '2018-06-30',
               ...
               '2007-05-31', '2007-02-28', '2006-11-30', '2006-08-31',
               '2006-05-31', '2006-02-28', '2005-11-30', '2005-08-31',
               '2005-05-31', '2005-02-28'],
              dtype='datetime64[ns]', length=191, freq=None)

In [14]:
df.sort_index(ascending = False)

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,...,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.87,...,NaN,NaN,NaN,NaN,NaN,0.91,NaN,NaN,NaN,NaN
2020-09-30,3.96,1.44,2.41,0.41,0.24,1.71,0.98,1.24,1.65,NaN,...,NaN,0.69,7.8,-6.98,0.92,NaN,2.01,1.19,2.47,10.13
2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.92,...,NaN,NaN,NaN,NaN,NaN,0.86,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.59,...,NaN,NaN,NaN,NaN,NaN,0.59,NaN,NaN,NaN,NaN
2005-03-31,0.58,0.40,-16.26,0.13,NaN,NaN,1.21,NaN,0.62,NaN,...,NaN,1.06,1.0,0.86,0.82,NaN,2.63,0.26,2.03,1.03
2005-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.43,...,NaN,NaN,NaN,NaN,NaN,0.53,NaN,NaN,NaN,NaN

In [15]:
df.resample('Q', convention = 'end').agg('mean')

,AAPL,MSFT,AMZN,GOOG,FB,TSLA,BRK.A,V,JNJ,WMT,...,COST,CVX,LLY,MCD,DHR,MDT,NEE,TXN,HON,UPS
2005-03-31,0.58,0.40,-16.26,0.13,NaN,NaN,1.21,NaN,0.62,1.43,...,0.91,1.06,1.00,0.86,0.82,0.53,2.63,0.26,2.03,1.03
2005-06-30,0.54,0.47,-41.64,0.14,NaN,NaN,1.21,NaN,0.55,1.59,...,0.89,1.04,1.28,0.88,0.81,0.59,2.63,0.26,1.83,1.02
2005-09-30,0.55,0.48,471.00,0.08,NaN,NaN,1.20,NaN,0.54,1.61,...,0.88,1.07,1.18,0.92,0.81,0.60,3.01,0.26,1.83,1.11
2005-12-31,0.69,0.52,14.02,0.09,NaN,NaN,1.17,NaN,0.52,1.64,...,0.92,1.01,1.28,0.98,0.80,0.60,2.85,0.26,1.94,1.07
2006-03-31,0.60,0.59,8.23,0.10,NaN,NaN,1.41,NaN,0.51,1.60,...,0.89,0.97,1.07,0.95,0.74,0.56,2.67,0.25,1.95,1.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-31,2.80,1.57,2.63,0.37,0.32,3.60,0.91,1.12,1.65,2.06,...,2.17,0.64,13.56,-6.79,1.05,0.80,1.85,1.02,2.14,16.62
2020-03-31,3.09,1.49,2.39,0.34,0.31,2.71,1.03,1.11,1.53,1.90,...,1.87,0.63,11.86,-6.44,1.22,0.79,1.95,1.24,2.21,17.38
2020-06-30,3.39,1.55,2.50,0.34,0.27,2.56,0.98,1.19,1.52,2.14,...,2.01,0.66,8.82,-6.28,0.97,0.78,1.93,1.28,2.46,13.18
2020-09-30,3.96,1.44,2.41,0.41,0.24,1.71,0.98,1.24,1.65,1.92,...,1.97,0.69,7.80,-6.98,0.92,0.86,2.01,1.19,2.47,10.13
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.87,...,2.93,NaN,NaN,NaN,NaN,0.91,NaN,NaN,NaN,NaN

In [16]:
df.resample('Q', convention = 'end').agg('mean').transpose()

,2005-03-31,2005-06-30,2005-09-30,2005-12-31,2006-03-31,2006-06-30,2006-09-30,2006-12-31,2007-03-31,2007-06-30,...,2018-09-30,2018-12-31,2019-03-31,2019-06-30,2019-09-30,2019-12-31,2020-03-31,2020-06-30,2020-09-30,2020-12-31
AAPL,0.58,0.54,0.55,0.69,0.60,0.62,0.72,0.73,0.53,0.62,...,2.41,2.17,2.23,2.34,2.74,2.80,3.09,3.39,3.96,NaN
MSFT,0.40,0.47,0.48,0.52,0.59,0.74,0.81,0.81,0.83,1.03,...,2.00,1.81,1.78,1.80,1.63,1.57,1.49,1.55,1.44,NaN
AMZN,-16.26,-41.64,471.00,14.02,8.23,7.26,15.67,9.12,9.37,6.24,...,2.67,2.74,2.68,2.61,2.52,2.63,2.39,2.50,2.41,NaN
GOOG,0.13,0.14,0.08,0.09,0.10,0.08,0.09,0.08,0.09,0.09,...,0.30,0.31,0.34,0.34,0.35,0.37,0.34,0.34,0.41,NaN
FB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.15,0.16,0.27,0.32,0.32,0.32,0.31,0.27,0.24,NaN
TSLA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.52,4.17,4.29,3.85,3.77,3.60,2.71,2.56,1.71,NaN
BRK.A,1.21,1.21,1.20,1.17,1.41,1.38,1.35,1.29,1.38,1.33,...,0.94,1.01,0.98,0.97,0.96,0.91,1.03,0.98,0.98,NaN
V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,...,1.04,1.10,1.04,1.01,1.09,1.12,1.11,1.19,1.24,NaN
JNJ,0.62,0.55,0.54,0.52,0.51,0.50,0.51,0.79,0.79,0.73,...,1.41,1.56,1.55,1.55,1.67,1.65,1.53,1.52,1.65,NaN
WMT,1.43,1.59,1.61,1.64,1.60,1.64,1.57,1.57,1.46,1.59,...,1.79,1.85,1.75,2.13,2.05,2.06,1.90,2.14,1.92,1.87
JPM,10.19,10.11,10.34,10.18,10.75,11.00,10.78,10.67,10.97,11.23,...,9.10,9.22,9.53,9.36,9.46,9.28,11.02,11.15,10.97,NaN
MA,2.13,1.97,1.97,2.17,1.84,1.19,1.10,1.15,1.00,0.96,...,3.03,3.59,3.53,3.91,4.22,3.94,4.65,3.94,4.40,NaN
PG,2.37,2.33,3.26,1.06,1.10,1.16,1.15,1.10,1.04,1.07,...,1.26,1.27,1.19,1.42,1.43,1.43,1.58,1.58,1.47,NaN
UNH,1.67,1.71,1.65,1.32,1.55,1.59,1.38,1.32,1.42,1.52,...,1.87,1.80,1.96,1.99,2.01,1.88,2.16,1.89,1.80,NaN
DIS,1.04,0.99,1.03,1.12,1.07,0.82,0.89,0.88,0.88,0.89,...,0.87,0.84,1.05,1.17,1.07,1.12,1.17,1.30,1.28,NaN
NVDA,0.38,0.33,0.36,0.34,0.31,0.34,0.32,0.37,0.33,0.34,...,0.47,0.44,0.42,0.45,0.43,0.41,0.42,0.78,0.81,0.75
HD,0.62,0.76,0.70,0.73,0.65,0.90,0.90,0.90,1.09,1.18,...,22.01,33.24,-24.43,-25.04,-45.84,-49.35,-17.44,-17.83,-154.02,42.60
PYPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.89,1.82,2.05,2.00,2.05,2.03,2.39,2.57,2.54,NaN
BAC,11.31,11.40,11.37,11.72,9.62,10.31,9.85,9.79,10.14,10.30,...,7.92,7.87,7.90,7.83,8.04,8.19,8.89,9.32,9.19,NaN
VZ,3.34,3.39,3.29,3.24,3.08,3.11,3.01,2.89,2.78,2.71,...,3.74,3.84,3.94,3.89,3.72,3.64,3.78,3.57,3.46,NaN
ADBE,0.31,0.30,0.25,0.31,0.14,0.15,0.14,0.16,0.16,0.18,...,0.74,1.01,0.98,0.98,0.96,0.97,1.03,0.99,0.91,0.83
CMCSA,1.52,1.54,1.52,1.57,1.57,1.58,1.65,1.68,1.64,1.65,...,1.77,2.47,2.38,2.30,2.24,2.14,2.17,2.14,2.07,NaN
NFLX,0.67,0.63,0.56,0.61,0.65,0.40,0.42,0.47,0.45,0.38,...,3.66,3.96,3.77,3.94,3.51,3.48,3.17,2.98,2.74,NaN
KO,0.92,0.82,0.81,0.80,0.82,0.77,0.74,0.77,0.92,1.11,...,3.31,3.37,3.46,3.43,3.23,3.09,3.74,3.94,3.78,NaN
NKE,0.59,0.56,0.53,0.50,0.52,0.57,0.54,0.50,0.49,0.52,...,1.50,1.60,1.56,1.62,1.85,1.85,1.90,2.89,2.61,2.27
MRK,1.44,1.47,1.47,1.50,1.30,1.25,1.27,1.54,1.33,1.27,...,1.61,2.07,1.98,2.03,2.10,2.25,2.23,2.27,2.07,NaN
PEP,1.06,1.09,1.19,1.23,1.10,1.06,1.02,0.95,0.94,1.01,...,6.09,4.32,4.28,4.35,4.45,4.28,5.27,6.11,5.77,NaN
T,1.65,1.61,1.59,1.66,1.62,1.60,1.60,1.34,1.35,1.39,...,1.89,1.74,1.81,1.82,1.82,1.73,1.79,1.83,1.76,NaN
PFE,0.82,0.72,0.65,0.78,0.62,0.63,0.56,0.62,0.52,0.62,...,1.34,1.50,1.63,1.61,1.61,1.64,1.55,1.76,1.73,NaN
INTC,0.26,0.24,0.29,0.34,0.37,0.33,0.34,0.32,0.30,0.27,...,0.79,0.72,0.76,0.75,0.80,0.76,0.94,0.86,0.95,NaN
CRM,0.93,0.93,0.96,0.98,1.21,1.16,1.18,1.17,1.36,1.26,...,0.91,0.81,0.97,1.02,0.94,0.50,0.63,0.55,0.50,0.47
ABT,1.04,0.93,1.02,1.02,0.98,1.24,1.13,1.57,1.53,1.42,...,1.32,1.19,1.17,1.15,1.14,1.17,1.20,1.23,1.19,NaN
ORCL,1.41,0.91,0.73,0.60,0.89,0.93,0.94,0.87,0.86,1.04,...,2.33,2.81,3.52,3.86,4.59,5.08,5.50,8.08,10.20,11.77
ABBV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-23.65,-8.03,-8.25,-7.67,-8.23,-11.91,-13.30,9.15,8.79,NaN
CSCO,0.42,0.43,0.46,0.48,0.47,0.75,0.81,0.76,0.74,0.71,...,1.52,1.40,1.51,1.64,1.91,1.69,1.55,1.56,1.50,1.49
TMO,0.33,0.54,0.50,0.52,0.48,0.53,0.49,0.53,0.49,0.46,...,1.05,1.04,1.01,1.02,0.93,0.97,1.06,1.06,1.01,NaN
AVGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.84,0.88,2.11,2.20,2.25,1.71,2.32,2.41,2.37,2.18
XOM,0.94,0.93,0.94,0.87,0.92,0.91,0.92,0.92,0.96,0.96,...,0.80,0.74,0.80,0.82,0.82,0.82,0.89,0.93,0.94,NaN
ACN,3.95,4.13,4.28,5.97,6.00,5.08,4.01,4.35,3.97,4.35,...,1.28,1.05,1.00,0.99,1.01,1.13,1.10,1.13,1.12,1.08
QCOM,0.12,0.11,0.12,0.12,0.11,0.13,0.13,0.15,0.15,0.16,...,39.54,8.47,7.80,5.25,5.71,6.34,9.49,8.78,4.86,NaN
COST,0.91,0.89,0.88,0.92,0.89,0.87,0.91,1.05,1.04,1.30,...,2.12,2.25,2.02,1.95,1.91,2.17,1.87,2.01,1.97,2.93
CVX,1.06,1.04,1.07,1.01,0.97,0.96,0.93,0.92,0.90,0.88,...,0.66,0.63,0.65,0.63,0.64,0.64,0.63,0.66,0.69,NaN
LLY,1.00,1.28,1.18,1.28,1.07,1.05,0.83,1.00,1.06,1.08,...,2.15,3.03,13.82,12.53,9.94,13.56,11.86,8.82,7.80,NaN
MCD,0.86,0.88,0.92,0.98,0.95,0.90,0.99,0.87,0.87,0.92,...,-6.01,-6.24,-8.09,-7.79,-6.33,-6.79,-6.44,-6.28,-6.98,NaN
DHR,0.82,0.81,0.81,0.80,0.74,1.03,0.95,0.94,0.86,0.79,...,0.72,0.70,0.64,0.66,0.85,1.05,1.22,0.97,0.92,NaN
MDT,0.53,0.59,0.60,0.60,0.56,1.10,1.04,0.84,0.78,0.78,...,0.78,0.77,0.78,0.79,0.81,0.80,0.79,0.78,0.86,0.91
NEE,2.63,2.63,3.01,2.85,2.67,2.72,2.64,2.61,2.60,2.66,...,1.64,1.77,1.88,1.88,1.84,1.85,1.95,1.93,2.01,NaN
TXN,0.26,0.26,0.26,0.26,0.25,0.25,0.23,0.23,0.22,0.22,...,0.77,0.91,1.05,1.05,1.00,1.02,1.24,1.28,1.19,NaN
HON,2.03,1.83,1.83,1.94,1.95,1.96,1.89,2.18,2.41,3.07,...,2.36,2.15,2.09,2.20,2.28,2.14,2.21,2.46,2.47,NaN
UPS,1.03,1.02,1.11,1.07,1.08,1.05,1.11,1.15,1.18,1.20,...,13.94,15.47,13.94,10.94,8.56,16.62,17.38,13.18,10.13,NaN

In [18]:
col = df.resample('Q', convention = 'end').agg('mean').transpose()['2020-09-30']

In [19]:
result = (col < 5) & (col > 0)

In [21]:
result.name = 'D/E Ratio'

In [22]:
result

AAPL      True
MSFT      True
AMZN      True
GOOG      True
FB        True
TSLA      True
BRK.A     True
V         True
JNJ       True
WMT       True
JPM      False
MA        True
PG        True
UNH       True
DIS       True
NVDA      True
HD       False
PYPL      True
BAC      False
VZ        True
ADBE      True
CMCSA     True
NFLX      True
KO        True
NKE       True
MRK       True
PEP      False
T         True
PFE       True
INTC      True
CRM       True
ABT       True
ORCL     False
ABBV     False
CSCO      True
TMO       True
AVGO      True
XOM       True
ACN       True
QCOM      True
COST      True
CVX       True
LLY      False
MCD      False
DHR       True
MDT       True
NEE       True
TXN       True
HON       True
UPS      False
Name: D/E Ratio, dtype: bool